//! Safe wrappers over the few parts of FFmpeg that iterframes uses:
//! demuxing, decoding (on the CPU or on a hardware device), and converting
//! frames to RGB24. Every call into FFmpeg lives in this module.

use std::ffi::{CStr, CString, c_char, c_int};
use std::fmt;
use std::ptr::{self, NonNull};

/// Bindings generated by build.rs, plus the error macros bindgen cannot
/// translate.
#[allow(
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    dead_code,
    unnecessary_transmutes,
    clippy::all
)]
mod sys {
    use std::ffi::c_int;

    include!(concat!(env!("OUT_DIR"), "/ffmpeg.rs"));

    pub const fn AVERROR(errno: c_int) -> c_int {
        -errno
    }

    pub const fn AVUNERROR(error: c_int) -> c_int {
        -error
    }

    /// `FFERRTAG`: the negated four-character code of an FFmpeg error.
    const fn tag(code: &[u8; 4]) -> c_int {
        -(u32::from_le_bytes(*code) as c_int)
    }

    /// `AV_NOPTS_VALUE`: no timestamp, which bindgen leaves behind with
    /// the other macros that cast.
    pub const AV_NOPTS_VALUE: i64 = i64::MIN;

    pub const AVERROR_EOF: c_int = tag(b"EOF ");
    pub const AVERROR_INVALIDDATA: c_int = tag(b"INDA");
    pub const AVERROR_EXTERNAL: c_int = tag(b"EXT ");
}

pub use sys::AVPixelFormat as PixelFormat;

/// An FFmpeg error code, always negative.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Error(c_int);

impl Error {
    pub const OUT_OF_MEMORY: Self = Self(sys::AVERROR(libc::ENOMEM));

    pub const INVALID_DATA: Self = Self(sys::AVERROR_INVALIDDATA);

    const EOF: Error = Error(sys::AVERROR_EOF);

    /// The POSIX error number, when the error comes from the system rather
    /// than from FFmpeg itself.
    pub fn errno(self) -> Option<c_int> {
        // FFmpeg's own errors are four-letter tags, far below any errno.
        let errno = sys::AVUNERROR(self.0);
        (1..4096).contains(&errno).then_some(errno)
    }
}

impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let mut buffer = [0 as c_char; sys::AV_ERROR_MAX_STRING_SIZE as usize];
        // SAFETY: av_strerror writes a NUL-terminated string that fits in
        // the buffer, even for unknown codes.
        let message = unsafe {
            sys::av_strerror(self.0, buffer.as_mut_ptr(), buffer.len());
            CStr::from_ptr(buffer.as_ptr())
        };
        f.write_str(&message.to_string_lossy())
    }
}

/// Turn a negative return value into an error.
fn check(code: c_int) -> Result<c_int, Error> {
    if code < 0 { Err(Error(code)) } else { Ok(code) }
}

/// Keep FFmpeg quiet: errors reach Python as exceptions, and the ones it
/// logs are either repeated there or expected, such as a missing NVIDIA
/// driver while `device="auto"` probes for a device.
pub fn init() {
    // SAFETY: plain setter of a global.
    unsafe { sys::av_log_set_level(sys::AV_LOG_QUIET) };
}

/// Version of the FFmpeg that the module is linked to, such as `9.0.2`.
pub fn version() -> String {
    // SAFETY: av_version_info returns a static NUL-terminated string.
    unsafe { CStr::from_ptr(sys::av_version_info()) }
        .to_string_lossy()
        .into_owned()
}

/// An open media file.
pub struct Input(NonNull<sys::AVFormatContext>);

impl Input {
    pub fn open(path: &str) -> Result<Self, Error> {
        let path = CString::new(path).map_err(|_| Error(sys::AVERROR(libc::EINVAL)))?;
        let mut context = ptr::null_mut();
        // SAFETY: on failure avformat_open_input frees the context and
        // leaves the pointer null; on success `Input` owns it.
        unsafe {
            check(sys::avformat_open_input(
                &mut context,
                path.as_ptr(),
                ptr::null(),
                ptr::null_mut(),
            ))?;
            let input = Self(NonNull::new(context).ok_or(Error::OUT_OF_MEMORY)?);
            check(sys::avformat_find_stream_info(
                input.0.as_ptr(),
                ptr::null_mut(),
            ))?;
            Ok(input)
        }
    }

    /// Open a decoder for the best video stream of the file. With a
    /// `device`, libavcodec decodes on it whenever it supports the codec,
    /// and on the CPU otherwise. `width` and `height` are the size the
    /// caller wants: NVIDIA decoders resize to it while decoding, the
    /// others leave it to the `Scaler`.
    pub fn video_decoder(
        &self,
        device: Option<&HwDevice>,
        width: Option<u32>,
        height: Option<u32>,
    ) -> Result<Decoder, Error> {
        let mut codec = ptr::null();
        // SAFETY: the context is open; the stream index returned is valid
        // for its `streams` array, and the codec context is freed by
        // `Decoder` whether or not opening it succeeds.
        unsafe {
            let index = check(sys::av_find_best_stream(
                self.0.as_ptr(),
                sys::AVMediaType::AVMEDIA_TYPE_VIDEO,
                -1,
                -1,
                &mut codec,
                0,
            ))?;
            let stream = *(*self.0.as_ptr()).streams.add(index as usize);
            let parameters = (*stream).codecpar;
            let cuvid = match device {
                Some(device) if device.kind.0 == sys::AVHWDeviceType::AV_HWDEVICE_TYPE_CUDA => {
                    cuvid_decoder((*parameters).codec_id)
                }
                _ => None,
            };
            if let Some(cuvid) = cuvid {
                codec = cuvid;
            }
            let context =
                NonNull::new(sys::avcodec_alloc_context3(codec)).ok_or(Error::OUT_OF_MEMORY)?;
            let decoder = Decoder {
                context,
                stream: index as usize,
            };
            check(sys::avcodec_parameters_to_context(
                context.as_ptr(),
                parameters,
            ))?;
            if cuvid.is_some() && (width.is_some() || height.is_some()) {
                let size = format!(
                    "{}x{}",
                    width.unwrap_or((*parameters).width as u32),
                    height.unwrap_or((*parameters).height as u32),
                );
                let size = CString::new(size).expect("no NUL in a size");
                check(sys::av_opt_set(
                    (*context.as_ptr()).priv_data,
                    c"resize".as_ptr(),
                    size.as_ptr(),
                    0,
                ))?;
            }
            // libavcodec decodes on a single thread unless asked otherwise;
            // a count of 0 lets it pick one thread per core.
            (*context.as_ptr()).thread_type = sys::FF_THREAD_FRAME as c_int;
            (*context.as_ptr()).thread_count = 0;
            if let Some(device) = device {
                // The codec context takes its own reference and drops it
                // when freed.
                (*context.as_ptr()).hw_device_ctx = sys::av_buffer_ref(device.device.as_ptr());
            }
            check(sys::avcodec_open2(context.as_ptr(), codec, ptr::null_mut()))?;
            Ok(decoder)
        }
    }

    /// Read the next packet into `packet`. Return `false` at the end of
    /// the file.
    pub fn read(&mut self, packet: &mut Packet) -> Result<bool, Error> {
        loop {
            // SAFETY: both pointers are valid; av_read_frame expects a blank
            // packet, hence the unref.
            let code = unsafe {
                sys::av_packet_unref(packet.0.as_ptr());
                sys::av_read_frame(self.0.as_ptr(), packet.0.as_ptr())
            };
            match check(code) {
                Ok(_) => return Ok(true),
                Err(Error::EOF) => return Ok(false),
                // The demuxer resyncs past a corrupt packet.
                Err(Error::INVALID_DATA) => continue,
                Err(err) => return Err(err),
            }
        }
    }

    /// Move the demuxer to the last key frame of `stream` at or before
    /// `timestamp`, in the time base of that stream. The decoder must be
    /// flushed afterwards, since its buffered frames come from elsewhere
    /// in the file.
    pub fn seek(&mut self, stream: usize, timestamp: i64) -> Result<(), Error> {
        // SAFETY: the context is open and `stream` is one of its streams.
        check(unsafe {
            sys::avformat_seek_file(
                self.0.as_ptr(),
                stream as c_int,
                i64::MIN,
                timestamp,
                timestamp,
                0,
            )
        })
        .map(drop)
    }
}

impl Drop for Input {
    fn drop(&mut self) {
        let mut context = self.0.as_ptr();
        // SAFETY: the context was opened by avformat_open_input.
        unsafe { sys::avformat_close_input(&mut context) };
    }
}

pub struct Packet(NonNull<sys::AVPacket>);

impl Packet {
    pub fn new() -> Self {
        // SAFETY: allocation only; a null result means out of memory, which
        // Rust treats as fatal too.
        Self(NonNull::new(unsafe { sys::av_packet_alloc() }).expect("out of memory"))
    }

    pub fn stream(&self) -> usize {
        // SAFETY: the packet is allocated.
        unsafe { (*self.0.as_ptr()).stream_index as usize }
    }

    /// When the frame in the packet is shown, or `None` when the container
    /// does not say.
    pub fn pts(&self) -> Option<i64> {
        // SAFETY: the packet is allocated.
        let pts = unsafe { (*self.0.as_ptr()).pts };
        (pts != sys::AV_NOPTS_VALUE).then_some(pts)
    }

    /// When the frame in the packet is decoded, which containers that have
    /// no `pts` still give.
    pub fn dts(&self) -> Option<i64> {
        // SAFETY: the packet is allocated.
        let dts = unsafe { (*self.0.as_ptr()).dts };
        (dts != sys::AV_NOPTS_VALUE).then_some(dts)
    }

    /// Whether the packet holds a key frame, which decoding can start from.
    pub fn is_key(&self) -> bool {
        // SAFETY: the packet is allocated.
        unsafe { (*self.0.as_ptr()).flags & sys::AV_PKT_FLAG_KEY as c_int != 0 }
    }
}

impl Drop for Packet {
    fn drop(&mut self) {
        let mut packet = self.0.as_ptr();
        // SAFETY: allocated by av_packet_alloc.
        unsafe { sys::av_packet_free(&mut packet) };
    }
}

/// An open video decoder.
pub struct Decoder {
    context: NonNull<sys::AVCodecContext>,
    stream: usize,
}

impl Decoder {
    /// Index of the stream this decoder reads.
    pub fn stream(&self) -> usize {
        self.stream
    }

    pub fn send(&mut self, packet: &Packet) -> Result<(), Error> {
        // SAFETY: the decoder is open and the packet allocated.
        check(unsafe { sys::avcodec_send_packet(self.context.as_ptr(), packet.0.as_ptr()) })
            .map(drop)
    }

    /// Signal the end of the stream, so that the buffered frames come out.
    pub fn send_eof(&mut self) -> Result<(), Error> {
        // SAFETY: a null packet is how libavcodec is told to drain.
        check(unsafe { sys::avcodec_send_packet(self.context.as_ptr(), ptr::null()) }).map(drop)
    }

    /// Throw away the buffered frames, after seeking elsewhere in the
    /// file.
    pub fn flush(&mut self) {
        // SAFETY: the decoder is open.
        unsafe { sys::avcodec_flush_buffers(self.context.as_ptr()) };
    }

    /// Move the next decoded frame into `frame`. Return `false` when the
    /// decoder needs more input, is drained, or failed on this frame; like
    /// the ffmpeg command, decoding goes on after a broken frame.
    pub fn receive(&mut self, frame: &mut Frame) -> bool {
        // SAFETY: the decoder is open and the frame allocated.
        unsafe { sys::avcodec_receive_frame(self.context.as_ptr(), frame.0.as_ptr()) >= 0 }
    }
}

impl Drop for Decoder {
    fn drop(&mut self) {
        let mut context = self.context.as_ptr();
        // SAFETY: allocated by avcodec_alloc_context3.
        unsafe { sys::avcodec_free_context(&mut context) };
    }
}

/// A video frame.
pub struct Frame(NonNull<sys::AVFrame>);

// SAFETY: an AVFrame has no thread affinity, and `Frame` only hands out
// shared access to its pixels through `&self`.
unsafe impl Send for Frame {}
unsafe impl Sync for Frame {}

impl Frame {
    pub fn new() -> Self {
        // SAFETY: allocation only.
        Self(NonNull::new(unsafe { sys::av_frame_alloc() }).expect("out of memory"))
    }

    fn get(&self) -> &sys::AVFrame {
        // SAFETY: the frame is allocated for as long as `self` lives.
        unsafe { self.0.as_ref() }
    }

    pub fn width(&self) -> u32 {
        self.get().width as u32
    }

    pub fn height(&self) -> u32 {
        self.get().height as u32
    }

    /// When the frame is shown, in the time base of its stream, or `None`
    /// when the file does not say.
    pub fn pts(&self) -> Option<i64> {
        let pts = self.get().best_effort_timestamp;
        (pts != sys::AV_NOPTS_VALUE).then_some(pts)
    }

    fn format(&self) -> c_int {
        self.get().format
    }

    /// Whether the pixels live on a hardware device rather than in memory.
    pub fn is_hardware(&self) -> bool {
        !self.get().hw_frames_ctx.is_null()
    }

    /// Make the pixels of a hardware frame readable from the CPU: map them
    /// where the device allows it, as VideoToolbox does, and copy them
    /// otherwise.
    pub fn download(&self) -> Result<Frame, Error> {
        let frame = Frame::new();
        // SAFETY: `self` is a hardware frame and `frame` a blank one. A
        // mapped frame holds a reference to the hardware one, so it stays
        // valid after `self` is reused.
        unsafe {
            let flags = sys::AV_HWFRAME_MAP_READ.0 as c_int;
            if sys::av_hwframe_map(frame.0.as_ptr(), self.0.as_ptr(), flags) < 0 {
                sys::av_frame_unref(frame.0.as_ptr());
                check(sys::av_hwframe_transfer_data(
                    frame.0.as_ptr(),
                    self.0.as_ptr(),
                    0,
                ))?;
            }
        }
        Ok(frame)
    }

    /// How the pixels of a hardware frame are laid out on the device, such
    /// as NV12, or `None` for a frame in memory.
    pub fn hardware_format(&self) -> Option<sys::AVPixelFormat> {
        let frames = self.get().hw_frames_ctx;
        // SAFETY: the hw_frames_ctx of a frame references an
        // AVHWFramesContext.
        (!frames.is_null())
            .then(|| unsafe { (*(*frames).data.cast::<sys::AVHWFramesContext>()).sw_format })
    }

    /// Bytes from the start of one row of `plane` to the next.
    pub fn stride(&self, plane: usize) -> usize {
        self.get().linesize[plane] as usize
    }

    /// Pointer to the first pixel of `plane`. Writing through it is up to
    /// the caller, who must know nothing else reads the pixels meanwhile.
    pub fn data(&self, plane: usize) -> *mut u8 {
        self.get().data[plane]
    }
}

impl Drop for Frame {
    fn drop(&mut self) {
        let mut frame = self.0.as_ptr();
        // SAFETY: allocated by av_frame_alloc.
        unsafe { sys::av_frame_free(&mut frame) };
    }
}

/// Waiting on the CUDA stream that the NVIDIA decoders copy frames on, with
/// the CUDA driver that FFmpeg itself loads at run time.
pub mod cuda {
    use std::ffi::{CStr, c_char, c_int, c_void};
    use std::ptr;
    use std::sync::OnceLock;

    use super::{Error, Frame, sys};

    /// `AVCUDADeviceContext` from `libavutil/hwcontext_cuda.h`, which
    /// bindgen cannot read without CUDA's own headers.
    #[repr(C)]
    struct DeviceContext {
        context: *mut c_void,
        stream: *mut c_void,
        internal: *mut c_void,
    }

    /// A driver function taking a handle, such as a context or a stream.
    /// The driver API is `__stdcall` on Windows, hence `"system"`.
    type WithHandle = unsafe extern "system" fn(*mut c_void) -> c_int;
    /// A driver function writing its result through a pointer.
    type WithOutput<T> = unsafe extern "system" fn(*mut T) -> c_int;

    /// The few driver functions needed, all returning a `CUresult`.
    struct Driver {
        push_context: WithHandle,
        pop_context: WithOutput<*mut c_void>,
        synchronize: WithHandle,
        device: WithOutput<c_int>,
    }

    fn driver() -> Option<&'static Driver> {
        static DRIVER: OnceLock<Option<Driver>> = OnceLock::new();
        DRIVER
            .get_or_init(|| {
                // SAFETY: the symbols have the signatures of the CUDA driver
                // API, and the library stays loaded for good.
                unsafe {
                    let library = open_driver()?;
                    let symbol = |name: &CStr| {
                        let symbol = find_symbol(library, name.as_ptr());
                        (!symbol.is_null()).then_some(symbol)
                    };
                    Some(Driver {
                        push_context: std::mem::transmute::<*mut c_void, WithHandle>(symbol(
                            c"cuCtxPushCurrent_v2",
                        )?),
                        pop_context: std::mem::transmute::<*mut c_void, WithOutput<*mut c_void>>(
                            symbol(c"cuCtxPopCurrent_v2")?,
                        ),
                        synchronize: std::mem::transmute::<*mut c_void, WithHandle>(symbol(
                            c"cuStreamSynchronize",
                        )?),
                        device: std::mem::transmute::<*mut c_void, WithOutput<c_int>>(symbol(
                            c"cuCtxGetDevice",
                        )?),
                    })
                }
            })
            .as_ref()
    }

    #[cfg(unix)]
    fn open_driver() -> Option<*mut c_void> {
        // SAFETY: the name is a valid C string.
        let library = unsafe { libc::dlopen(c"libcuda.so.1".as_ptr(), libc::RTLD_NOW) };
        (!library.is_null()).then_some(library)
    }

    #[cfg(unix)]
    unsafe fn find_symbol(library: *mut c_void, name: *const c_char) -> *mut c_void {
        // SAFETY: the caller passes a library that `open_driver` returned
        // and a valid C string.
        unsafe { libc::dlsym(library, name) }
    }

    #[cfg(windows)]
    #[link(name = "kernel32")]
    unsafe extern "system" {
        fn LoadLibraryA(name: *const c_char) -> *mut c_void;
        fn GetProcAddress(module: *mut c_void, name: *const c_char) -> *mut c_void;
    }

    #[cfg(windows)]
    fn open_driver() -> Option<*mut c_void> {
        // SAFETY: the name is a valid C string.
        let library = unsafe { LoadLibraryA(c"nvcuda.dll".as_ptr()) };
        (!library.is_null()).then_some(library)
    }

    #[cfg(windows)]
    unsafe fn find_symbol(library: *mut c_void, name: *const c_char) -> *mut c_void {
        // SAFETY: the caller passes a library that `open_driver` returned
        // and a valid C string.
        unsafe { GetProcAddress(library, name) }
    }

    fn check(result: c_int) -> Result<(), Error> {
        if result == 0 {
            Ok(())
        } else {
            Err(Error(sys::AVERROR_EXTERNAL))
        }
    }

    /// Wait until the pixels of `frame`, a CUDA frame, have been copied
    /// into it, and return the ordinal of the GPU that holds them.
    pub fn synchronize(frame: &Frame) -> Result<c_int, Error> {
        let driver = driver().ok_or(Error(sys::AVERROR(libc::ENOSYS)))?;
        // SAFETY: a CUDA frame references frames of a CUDA device, whose
        // context the driver calls run in, pushed and popped around them.
        unsafe {
            let frames = (*frame.get().hw_frames_ctx)
                .data
                .cast::<sys::AVHWFramesContext>();
            let device = (*(*frames).device_ref)
                .data
                .cast::<sys::AVHWDeviceContext>();
            let cuda = (*device).hwctx.cast::<DeviceContext>();
            check((driver.push_context)((*cuda).context))?;
            let mut ordinal = 0;
            let result = check((driver.synchronize)((*cuda).stream))
                .and_then(|()| check((driver.device)(&mut ordinal)));
            (driver.pop_context)(&mut ptr::null_mut());
            result.map(|()| ordinal)
        }
    }
}

/// The NVIDIA decoder for `codec`, such as `h264_cuvid`, if this FFmpeg has
/// one. Unlike the NVDEC hwaccel of the regular decoders, it can resize on
/// the GPU while decoding, so that only small frames reach memory.
fn cuvid_decoder(codec: sys::AVCodecID) -> Option<*const sys::AVCodec> {
    // SAFETY: avcodec_get_name returns a static string for any id.
    let name = unsafe { CStr::from_ptr(sys::avcodec_get_name(codec)) };
    let name = CString::new(format!("{}_cuvid", name.to_str().ok()?)).ok()?;
    // SAFETY: lookup by a NUL-terminated name.
    let decoder = unsafe { sys::avcodec_find_decoder_by_name(name.as_ptr()) };
    (!decoder.is_null()).then_some(decoder)
}

/// A kind of hardware decoder built into this FFmpeg, such as
/// `videotoolbox` or `cuda`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct DeviceType(sys::AVHWDeviceType);

impl DeviceType {
    /// Every kind this FFmpeg was built with.
    pub fn all() -> Vec<DeviceType> {
        let mut types = Vec::new();
        let mut current = sys::AVHWDeviceType::AV_HWDEVICE_TYPE_NONE;
        loop {
            // SAFETY: iterating from NONE is how the API is meant to be used.
            current = unsafe { sys::av_hwdevice_iterate_types(current) };
            if current == sys::AVHWDeviceType::AV_HWDEVICE_TYPE_NONE {
                return types;
            }
            types.push(DeviceType(current));
        }
    }

    /// The kind called `name`, if this FFmpeg was built with it.
    pub fn by_name(name: &str) -> Option<DeviceType> {
        Self::all().into_iter().find(|kind| kind.name() == name)
    }

    pub fn name(self) -> &'static str {
        // SAFETY: the names are static strings, non-null for built kinds.
        unsafe { CStr::from_ptr(sys::av_hwdevice_get_type_name(self.0)) }
            .to_str()
            .unwrap_or("unknown")
    }
}

/// An open hardware device, such as a GPU.
pub struct HwDevice {
    device: NonNull<sys::AVBufferRef>,
    kind: DeviceType,
}

impl HwDevice {
    /// Open the default device of `kind`. Fails when the machine has no
    /// such device or its driver cannot be loaded.
    pub fn new(kind: DeviceType) -> Result<Self, Error> {
        let mut device = ptr::null_mut();
        // SAFETY: on success `device` holds a reference that `HwDevice`
        // owns; on failure it stays null.
        check(unsafe {
            sys::av_hwdevice_ctx_create(&mut device, kind.0, ptr::null(), ptr::null_mut(), 0)
        })?;
        let device = NonNull::new(device).ok_or(Error::OUT_OF_MEMORY)?;
        Ok(Self { device, kind })
    }
}

impl Drop for HwDevice {
    fn drop(&mut self) {
        let mut device = self.device.as_ptr();
        // SAFETY: a reference created by av_hwdevice_ctx_create.
        unsafe { sys::av_buffer_unref(&mut device) };
    }
}

/// Converts frames of one size and pixel format to packed RGB24.
pub struct Scaler {
    context: NonNull<sys::SwsContext>,
    input: (c_int, u32, u32),
    output: (u32, u32),
}

impl Scaler {
    /// A scaler from frames like `frame` to RGB24 frames of the given size.
    pub fn new(frame: &Frame, width: u32, height: u32) -> Result<Self, Error> {
        let context =
            NonNull::new(unsafe { sys::sws_alloc_context() }).ok_or(Error::OUT_OF_MEMORY)?;
        let scaler = Self {
            context,
            input: (frame.format(), frame.width(), frame.height()),
            output: (width, height),
        };
        let options: [(&CStr, i64); 8] = [
            (c"srcw", frame.width().into()),
            (c"srch", frame.height().into()),
            (c"src_format", frame.format().into()),
            (c"dstw", width.into()),
            (c"dsth", height.into()),
            (c"dst_format", sys::AVPixelFormat::AV_PIX_FMT_RGB24.0.into()),
            (c"sws_flags", SWS_BILINEAR.into()),
            // Converting to RGB takes longer than decoding, which already
            // runs on several threads; 0 is one slice thread per core.
            (c"threads", 0),
        ];
        // SAFETY: the options exist on every SwsContext and take integers;
        // `scaler` frees the context if initializing it fails.
        unsafe {
            for (name, value) in options {
                check(sys::av_opt_set_int(
                    context.as_ptr().cast(),
                    name.as_ptr(),
                    value,
                    0,
                ))?;
            }
            check(sys::sws_init_context(
                context.as_ptr(),
                ptr::null_mut(),
                ptr::null_mut(),
            ))?;
        }
        Ok(scaler)
    }

    /// The size of the frames it makes, as `(width, height)`.
    pub fn output(&self) -> (u32, u32) {
        self.output
    }

    /// Whether `frame` has the size and pixel format this scaler expects.
    pub fn accepts(&self, frame: &Frame) -> bool {
        self.input == (frame.format(), frame.width(), frame.height())
    }

    /// Convert `frame`, which the scaler must accept, to a new RGB24 frame
    /// whose rows follow each other with no padding.
    pub fn run(&mut self, frame: &Frame) -> Result<Frame, Error> {
        let rgb = self.output_frame();
        // SAFETY: the frame is blank but for its size and format.
        // An alignment of 1 packs the rows, so that Python gets a
        // contiguous array without copying.
        check(unsafe { sys::av_frame_get_buffer(rgb.0.as_ptr(), 1) })?;
        self.scale(frame, &rgb)?;
        Ok(rgb)
    }

    /// Convert `frame`, which the scaler must accept, into `buffer` from
    /// byte `offset` on, as packed RGB24 rows.
    pub fn run_into(&mut self, frame: &Frame, buffer: &Buffer, offset: usize) -> Result<(), Error> {
        let (width, height) = (self.output.0 as usize, self.output.1 as usize);
        let stride = width * 3;
        assert!(
            offset + height * stride <= buffer.len(),
            "the frame does not fit in the buffer"
        );
        let rgb = self.output_frame();
        // SAFETY: the pixels written from data[0] stay within `buffer`, as
        // checked above, and the new reference keeps it alive until the
        // frame is freed.
        unsafe {
            let output = rgb.0.as_ptr();
            (*output).buf[0] = sys::av_buffer_ref(buffer.0.as_ptr());
            if (*output).buf[0].is_null() {
                return Err(Error::OUT_OF_MEMORY);
            }
            (*output).data[0] = buffer.data().add(offset);
            (*output).linesize[0] = stride as c_int;
        }
        self.scale(frame, &rgb)
    }

    /// A blank RGB24 frame of the output size.
    fn output_frame(&self) -> Frame {
        let rgb = Frame::new();
        // SAFETY: plain fields of a frame that owns no buffers yet.
        unsafe {
            let output = rgb.0.as_ptr();
            (*output).format = sys::AVPixelFormat::AV_PIX_FMT_RGB24.0;
            (*output).width = self.output.0 as c_int;
            (*output).height = self.output.1 as c_int;
        }
        rgb
    }

    fn scale(&mut self, frame: &Frame, rgb: &Frame) -> Result<(), Error> {
        debug_assert!(self.accepts(frame));
        // SAFETY: `rgb` has buffers for the output size and format;
        // `frame` is a decoded frame of the input size and format.
        check(unsafe {
            sys::sws_scale_frame(self.context.as_ptr(), rgb.0.as_ptr(), frame.0.as_ptr())
        })
        .map(|_| ())
    }
}

impl Drop for Scaler {
    fn drop(&mut self) {
        // SAFETY: allocated by sws_getContext.
        unsafe { sys::sws_freeContext(self.context.as_ptr()) };
    }
}

/// A reference-counted block of memory, for pixels that FFmpeg writes and
/// Python reads.
pub struct Buffer(NonNull<sys::AVBufferRef>);

// SAFETY: the reference count is atomic, and `Buffer` only hands out a
// pointer whose use is up to the caller.
unsafe impl Send for Buffer {}
unsafe impl Sync for Buffer {}

impl Buffer {
    /// `len` uninitialized bytes, aligned for SIMD.
    pub fn new(len: usize) -> Result<Self, Error> {
        // SAFETY: allocation only.
        NonNull::new(unsafe { sys::av_buffer_alloc(len) })
            .map(Self)
            .ok_or(Error::OUT_OF_MEMORY)
    }

    pub fn len(&self) -> usize {
        // SAFETY: the reference is valid for as long as `self` lives.
        unsafe { self.0.as_ref().size }
    }

    /// Pointer to the first byte. Writing through it is up to the caller,
    /// who must know nothing else reads the bytes meanwhile.
    pub fn data(&self) -> *mut u8 {
        // SAFETY: as in `len`.
        unsafe { self.0.as_ref().data }
    }
}

impl Drop for Buffer {
    fn drop(&mut self) {
        let mut buffer = self.0.as_ptr();
        // SAFETY: allocated by av_buffer_alloc.
        unsafe { sys::av_buffer_unref(&mut buffer) };
    }
}

/// `SWS_BILINEAR`, a macro before FFmpeg 8 and an enum from then on; the
/// value is the same in every version.
const SWS_BILINEAR: c_int = 2;
